linters:
  enable:
    - goheader

linters-settings:
  goheader:
    values:
      const:
        COMPANY: Cofide Limited
      regexp:
        VALID_YEAR: 202[4-9]|20[3-9][0-9]|2[1-9][0-9][0-9]
    # Require Cofide copyright and SPDX license in all source files.
    template: |
      Copyright {{ VALID_YEAR }} {{ COMPANY }}.
      SPDX-License-Identifier: Apache-2.0
